### PR TITLE
Dirty fix for oauth with LinkedIn, which requires full request URI in PO...

### PR DESCRIPTION
**Pull request by igorglotov**
Dirty fix for oauth with LinkedIn (https://developer.linkedin.com/documents/authentication, probably others), which requires full request URI in POST for auth token. This is ugly code but it works and I think you will fix it somehow. It's okay to decline it.

### CODE REVIEW

**Comment by stigi** [comment]
This is truly dirty ;)

Would you consider adding a toggle to enable that behavior?  
Also I'd suggest using the `-nxoauth2_URLByAddingParameters:` method from `NSURL+NXOAuth2`.

**Comment by airdrummingfool** [comment]
I had the same issue with LinkedIn. Turns out that they take GET requests for auth too, so all I did is override that method and set the `tokenRequest` `HTTPMethod` to `@"GET"`. Ideally, the request method would be settable somewhere.

**Comment by airdrummingfool** [comment]
See PR #111 for my attempt at making the `HTTPMethod` customizable.

**Comment by toto** [comment]
As #11 was merged I guess this is obsolete now.

**Pull request closed without merging**
