### PR TITLE
Fixed Instructions for iOS Projects

### LINKED ISSUE #15: Can never find NXOAuth2.h
Hello, I followed all the steps

1) Had to track down my libOAuth2Client.a manually via the debug simulator build folder and drag it to the Debug folder where the OAuth2Client.framework was successfully placed

2) Adding the "/tmp/OAuth2Client.dst/usr/local/include" to user header paths for both Target and Project, and both individually still nothing.

3) Using Xcode 4.1, building to iOS 4.3 simulator

Could you please post a sample project with it linked properly for reference. I feel as though I have tried every possible variation of the instructions to get it working please help!

Thanks,

Kieran

### PR DESCRIPTION
**Pull request by paularmstrong**
- Added a standard .gitignore for Obj-C projects (https://github.com/github/gitignore)
- Moved Copy Headers to Public list (fixed #15)
- Cleaned up iOS project setup instructions and added a missing step (`-ObjC` linker flag)

### CODE REVIEW

**Comment by toto** [comment]
Unfortunately your the fix for _Moved Copy Headers to Public list_ has a side effect. 

Try building a archive with this library linked in. It will copy the headers into a xcarchive but not produce a usable .ipa. This is different for static libs and Frameworks (because Frameworks are bundles). 

This is why we left them to private.  

To fix #15 we usually add `${SRCROOT}/OAuth2Client` to the header search path (provided you added the Project at that place. But I really would recommend using CocoaPods, as this will eliminate the problem and make your life happier :wink:

**Comment by paularmstrong** [comment]
Updated and moved them back. Seems to be working fine now. For some reason, it originally took both changes for things to work. Now it seems fine though!

**Comment by stigi** [comment]
@paularmstrong I merged it into the development branch (f04099cb50e44672283bc77f66dc9786f85b2123). Will end up in master in some minutes.

Did discard the project file settings since they should not have had any effect & also discarded some small whitespace changes in `README.md`. But the overall change is still present & you're name should still be in the git history :)

Thanks!

(Keeping this PR open. Think GitHub will close it automatically next time develop is merged into master)

**Comment by ionutale** [comment]
tried the CocoaPods, and i get this error
ERROR:  Error installing cocoapods:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/json-1.8.1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/json-1.8.1/ext/json/ext/generator/gem_make.out
www:~ ionutale$ 

( i just hate to be under pressure, nothing works out as it suppose to )

**Pull request merged**
