### PR TITLE
Patching Facebook incorrect response format

### PR DESCRIPTION
**Pull request by hsarret**

### CODE REVIEW

**Comment by toto** [comment]
Patching at the JSON response for a random (although big) service is not a good idea.  You should file a bug with Facebook, as this clearly is not the correct behavior. 

At some point we might provide a mechanism to hook into the response process, but currently this is not the right way to go.

**Comment by hsarret** [comment]
No problem at all. I agree it is an hackish way. And i wasn't really expecting you to accept that pull request.
But as it works i figured it could help others.
And it is way more visible on your repo than in my fork ;)

Cheers

**Comment by toto** [comment]
The FB SDK should be able to deal with this. Any reason you are not using their SDK?

**Comment by hsarret** [comment]
I need multi user and SDK can't seem to do that properly

**Comment by toto** [comment]
Good point. It's not really built for that.

**Comment by hsarret** [comment]
Lost enough time trying every other ways around (FB SDK, iOS native sharing) so figured WTH let's go closer to the metal ;)
And thanks to your great OAuth2Client, it's been quite fast ;)

**Pull request closed without merging**
