### PR TITLE
Adding the ability to configure the token request HTTP Method

### PR DESCRIPTION
**Pull request by airdrummingfool**
e.g. for LinkedIn, who wants all request params in the query string (and accepts GET requests).

### CODE REVIEW

**Comment by airdrummingfool** [comment]
Alternatively, instead of changing the HTTP method, we could instead have a configuration BOOL that tells the client to put the parameters in the URL instead of the request body. That might make more sense for #78.

**Comment by toto** [comment]
Sorry for taking so long to look at this.

Looks very useful. I will put this in (will merge this into develop though as we use [git-flow]() here). 

I will look at #78 separately.

**Comment by toto** [comment]
Merged into develop with d99998939df223531cee05962fa74f755ffbd697

**Comment by stigi** [comment]
@toto that sha you've just created looks so :imp: 

:scream: :scream_cat:

**Comment by toto** [comment]
Oh yeah!

**Pull request closed without merging**
